-- ============================================================
-- Run this ONCE in the Supabase SQL Editor before triggering the
-- legacy data migration. Safe to leave in place afterwards.
-- ============================================================

-- 1) Allow explicit IDs to be inserted (so migrated rows keep their
--    original integer IDs and all relationships stay intact).
alter table productions          alter column id set generated by default;
alter table agents               alter column id set generated by default;
alter table roles                alter column id set generated by default;
alter table artists              alter column id set generated by default;
alter table call_sheets          alter column id set generated by default;
alter table banners              alter column id set generated by default;
alter table call_sheet_artists   alter column id set generated by default;
alter table pencil_dates         alter column id set generated by default;
alter table fitting_dates        alter column id set generated by default;
alter table shoot_days           alter column id set generated by default;
alter table briefs               alter column id set generated by default;
alter table roles_to_fit         alter column id set generated by default;
alter table presentations        alter column id set generated by default;
alter table zcards               alter column id set generated by default;

-- 2) Helper function the import endpoint calls once all rows are in,
--    so future new rows (created through the app) get IDs after the
--    highest migrated ID instead of colliding with them.
create or replace function migration_reset_sequences() returns void as $$
declare
  t text;
begin
  for t in select unnest(array[
    'productions','agents','roles','artists','call_sheets','banners',
    'call_sheet_artists','pencil_dates','fitting_dates','shoot_days',
    'briefs','roles_to_fit','presentations','zcards'
  ])
  loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id)+1 from %I), 1), false)',
      t, t
    );
  end loop;
end;
$$ language plpgsql;
